# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\trpc.proto\x1a\x1bgoogle/protobuf/empty.proto\",\n\nApiRequest\x12\r\n\x05route\x18\x01 \x01(\t\x12\x0f\n\x07\x61rgData\x18\x02 \x01(\x0c\" \n\x0b\x41piResponse\x12\x11\n\treplyData\x18\x01 \x01(\x0c\"!\n\rRpcRoutesList\x12\x10\n\x08rpcRoute\x18\x01 \x03(\t2f\n\nServiceRPC\x12$\n\x07request\x12\x0b.ApiRequest\x1a\x0c.ApiResponse\x12\x32\n\x08listApis\x12\x16.google.protobuf.Empty\x1a\x0e.RpcRoutesListb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_APIREQUEST = _descriptor.Descriptor(
  name='ApiRequest',
  full_name='ApiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='route', full_name='ApiRequest.route', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='argData', full_name='ApiRequest.argData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=86,
)


_APIRESPONSE = _descriptor.Descriptor(
  name='ApiResponse',
  full_name='ApiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='replyData', full_name='ApiResponse.replyData', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=120,
)


_RPCROUTESLIST = _descriptor.Descriptor(
  name='RpcRoutesList',
  full_name='RpcRoutesList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rpcRoute', full_name='RpcRoutesList.rpcRoute', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['ApiRequest'] = _APIREQUEST
DESCRIPTOR.message_types_by_name['ApiResponse'] = _APIRESPONSE
DESCRIPTOR.message_types_by_name['RpcRoutesList'] = _RPCROUTESLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ApiRequest = _reflection.GeneratedProtocolMessageType('ApiRequest', (_message.Message,), {
  'DESCRIPTOR' : _APIREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:ApiRequest)
  })
_sym_db.RegisterMessage(ApiRequest)

ApiResponse = _reflection.GeneratedProtocolMessageType('ApiResponse', (_message.Message,), {
  'DESCRIPTOR' : _APIRESPONSE,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:ApiResponse)
  })
_sym_db.RegisterMessage(ApiResponse)

RpcRoutesList = _reflection.GeneratedProtocolMessageType('RpcRoutesList', (_message.Message,), {
  'DESCRIPTOR' : _RPCROUTESLIST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:RpcRoutesList)
  })
_sym_db.RegisterMessage(RpcRoutesList)



_SERVICERPC = _descriptor.ServiceDescriptor(
  name='ServiceRPC',
  full_name='ServiceRPC',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=157,
  serialized_end=259,
  methods=[
  _descriptor.MethodDescriptor(
    name='request',
    full_name='ServiceRPC.request',
    index=0,
    containing_service=None,
    input_type=_APIREQUEST,
    output_type=_APIRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='listApis',
    full_name='ServiceRPC.listApis',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_RPCROUTESLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICERPC)

DESCRIPTOR.services_by_name['ServiceRPC'] = _SERVICERPC

# @@protoc_insertion_point(module_scope)
